import{S as h,N as g,P as w}from"./assets/vendor-B25oHZNK.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();let f=null;function p(){window.innerWidth<1440&&!f?f=new h(".my-swiper",{modules:[g,w],slidesPerView:1,spaceBetween:16,loop:!0,navigation:{nextEl:".custom-next",prevEl:".custom-prev"},pagination:{el:".custom-pagination",clickable:!0}}):window.innerWidth>=1440&&f&&(f.destroy(!0,!0),f=null)}p();window.addEventListener("resize",p);document.querySelectorAll(".faq-acc-el-trigger").forEach(c=>{c.addEventListener("click",()=>{const o=c.closest(".faq-acc-el"),l=o.querySelector(".faq-acc-el-descr-frame");o.classList.contains("open")?(o.classList.remove("open"),l.style.maxHeight="0"):(o.classList.add("open"),l.style.maxHeight=l.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),o=c.querySelector(".icon"),l=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 5H20M4 12H20M4 19H20" stroke="#171717" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,n=`
<svg width="34" height="34" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M28.3334 28.3333L5.66675 5.66666M28.3334 5.66666L5.66675 28.3333" stroke="black" stroke-opacity="0.8" stroke-width="3.41667" stroke-linecap="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,o.innerHTML=t?n:a,t?i():s()}),d.forEach(u=>u.addEventListener("click",()=>{s(),o.innerHTML=a,t=!1})),window.addEventListener("scroll",r);function i(){l.style.display="block"}function s(){l.style.display="none"}function r(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const i=document.getElementById(n);if(!i)return;const s=c(),r=i.getBoundingClientRect().top+window.pageYOffset-s;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(i){const s=this.getAttribute("href");if(!s)return;const[r,u]=s.split("#");if(!u)return;const m=window.location.pathname.split("/").pop();!(r===""||r==="./"||r===m||r==="./"+m)||!document.getElementById(u)||(i.preventDefault(),o(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(s=>s.classList.remove("active"));const i=document.querySelector(`.navigation-item a[href*="#${n}"]`);i&&i.closest(".navigation-item").classList.add("active")}function a(){const n=window.pageYOffset+c()+100;d.forEach(i=>{const s=i.offsetTop,r=s+i.offsetHeight;n>=s&&n<r&&t(i.id)})}if(window.addEventListener("scroll",a),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
